utils::globalVariables(c(
  ".", "..evt", "..keep", "..keep_cols", "..maybe_cols", "..meta_cols", "..need",
  "..site_cols", ".__partner", ".__row__", ".__tx", ".bg_domains", ".fg_domains",
  "BLOSUM62", "BgRatio", "Count", "D1", "D2", "Description", "EXC_exc", "EXC_inc",
  "GeneID", "GeneRatio", "GeneRatio_num", "HITindex", "I1", "I2", "ID",
  "IJC_SAMPLE_1", "IPR", "IncLevel1", "M", "N", "N_adj", "OR", "SJC_SAMPLE_1", "V1",
  "a", "aa_end", "aa_start", "abs_start", "abs_stop", "absolute_exon_class",
  "absolute_exon_position", "ac", "all_zero", "alt_name", "any_dom_flag", "any_ppi",
  "b", "bg_prop", "cds_bp", "cds_bp_1", "cds_bp_2", "cds_end",
  "cds_gen_start", "cds_gen_stop", "cds_has", "cds_len", "cds_rel_start",
  "cds_rel_stop", "cds_start", "chr", "class_match", "class_pref_hit", "class_raw",
  "classification", "code_ord", "coding_exon_class", "coding_exon_position",
  "cond_label", "condition", "control", "count", "covered", "d", "d1", "d2",
  "database", "db", "delta_HIT", "delta_psi", "delta_psi_exc", "delta_psi_inc",
  "depth", "diff_HIT", "dom_key", "dom_kind", "domain", "domain_id", "domains",
  "domains_1", "domains_2", "either_domains_list", "ensembl_peptide_id",
  "ensembl_transcript_id", "et1", "et2", "event_count",
  "event_count_depth_corrected", "event_id", "event_key", "event_row", "event_type",
  "event_type_exc", "event_type_inc", "events", "evidence_id", "evidence_n", "exc",
  "exc_only_domains_list", "exc_only_flag", "exc_only_n", "exclusion_reads", "exon",
  "exon_aa_end", "exon_aa_start", "exon_bp_all_1", "exon_bp_all_2", "exon_end",
  "exon_id", "exon_ids", "exon_len", "exon_number", "exon_row", "exon_rows",
  "exon_start", "exons", "exons_exc", "exons_inc", "fdr", "feat_len", "feature_id",
  "feature_len", "feature_length", "fend", "fg_prop", "final_plot", "form", "frac",
  "frag_len", "frame_call", "frame_check_exon1", "frame_check_exon2", "fstart",
  "gen_start", "gen_stop", "gend", "gene", "gene_id", "gene_id_hit", "gene_name",
  "ggsave", "group", "gstart", "has", "has_neg", "has_pos", "has_ppi", "has_pro",
  "has_prot", "hit", "i.absolute_exon_class", "i.absolute_exon_position",
  "i.cds_abs_start", "i.cds_abs_stop", "i.cds_gen_start", "i.cds_gen_stop",
  "i.cds_has", "i.cds_len", "i.cds_rel_start", "i.cds_rel_stop",
  "i.coding_exon_class", "i.coding_exon_position", "i.ensembl_transcript_id",
  "i.exon_id", "i.gene_id", "i.start_codon_abs_start", "i.start_codon_abs_stop",
  "i.start_codon_gen_start", "i.start_codon_gen_stop", "i.start_codon_has",
  "i.start_codon_rel_start", "i.start_codon_rel_stop", "i.stop_codon_abs_start",
  "i.stop_codon_abs_stop", "i.stop_codon_gen_start", "i.stop_codon_gen_stop",
  "i.stop_codon_has", "i.stop_codon_rel_start", "i.stop_codon_rel_stop",
  "i.transcript_id", "i.utr_abs_start", "i.utr_abs_stop", "i.utr_gen_start",
  "i.utr_gen_stop", "i.utr_has", "i.utr_len", "i.utr_rel_start", "i.utr_rel_stop",
  "id", "inc", "inc_coord", "inc_exc", "inc_idx", "inc_inc",
  "inc_only_domains_list", "inc_only_flag", "inc_only_n", "inclusion_reads",
  "int_w", "int_width", "interpro", "interpro_end", "interpro_start", "jaccard",
  "k", "keep_pair", "key_cols", "kind", "label", "max_ex",
  "mean_events_per_gene", "mean_hit", "method", "ml10", "multi", "n", "nDOWN", "nFE",
  "nLE", "nUP", "n_abs", "n_coding", "n_cond", "n_events", "n_exc_ppi", "n_inc",
  "n_inc_ppi", "n_pairs_in_gene", "n_post", "n_ppi", "n_pre", "n_sig", "name",
  "next_exon_id", "ord", "ordA", "ordB", "overlap_aa_end", "overlap_aa_start",
  "overlap_end", "overlap_start", "p.value", "p_value", "padj", "partner_gene",
  "partner_tx", "pass", "pc_class", "pct", "peptide_id", "ppi_count",
  "ppi_direction", "present", "prop", "prop_any_ppi", "prot_aa", "prot_aa_1",
  "prot_aa_2", "prot_len", "prot_pid", "prot_score", "prot_start", "prot_stop",
  "protein_id", "protein_link", "protein_linked", "protein_seq",
  "protein_seq_exc", "protein_seq_inc", "psi", "psi_adj", "psi_mean",
  "psi_original", "psi_raw", "pval", "qvalue", "reads", "recip_q", "recip_s",
  "rel_offset", "rel_start", "rel_stop", "relative_use", "rend", "rescue", "row_id",
  "row_uid", "rstart", "sample_name", "save_path", "score", "site_id",
  "sizeFactor", "size_factors", "start_frame", "stop_frame", "strand",
  "strand_inc", "strand_num", "summary_classification", "t_ord", "tag", "test",
  "total", "total_sd_domains", "total_update", "transcript_id", "transcript_id_1",
  "transcript_id_2", "transcript_id_exc", "transcript_id_inc", "transcript_name",
  "transcript_row_uid", "transcript_seq", "transcript_seq_exc",
  "transcript_seq_inc", "transcript_support_level", "transcript_type",
  "transcript_uid", "transcript_uid_internal", "transcript_uid_terminal", "tx",
  "txA", "txB", "tx_gene", "type", "value", "value_exc", "value_inc",
  "source_file", "maxdiff", "uniq_hits", "n_test", "n_control", "cds_nt_end",
  "cds_nt_start", "clean_name", "d1_pruned", "d2_pruned", "genomic_end",
  "genomic_start", "grp", "i.end", "i.start", "na_genomic", "rmax",
  "transcript1", "transcript2", "inc_exons", "exc_exons"
))

# Additional NSE symbols referenced in data.table/ggplot calls across S4 and
# visualization helpers.
utils::globalVariables(c(
  "..cols_old", "..matched_cols", ".data",
  "DDI", "DDI_A", "DDI_B", "DDI_changed_case", "DDI_changed_control",
  "DMI", "DMI_A", "DMI_B", "DMI_changed_case", "DMI_changed_control",
  "ELMIdentifier", "End", "Primary_Acc", "Regex", "Start",
  "anchor_span", "c1", "c2",
  "case_only_flag", "case_only_n",
  "chr_1", "chr_2",
  "confirmed", "control_only_flag", "control_only_n",
  "coord", "cxmax", "cxmax_eps", "cxmin", "cxmin_eps",
  "delta_psi_case", "delta_psi_control",
  "di_key", "diff_n", "domain_name",
  "event_group", "ex_cxmin", "exc_case", "exc_control",
  "exon_alpha", "exon_idx", "exons_case", "exons_control",
  "fill",
  "geneA", "geneB", "gene_id_1", "gene_id_2",
  "gx1", "gx2", "gxmax", "gxmin",
  "has_value", "i.xmax", "i.xmin",
  "inc_case", "inc_control", "inc_exons_by_idx",
  "interaction_changed_case", "interaction_changed_control",
  "ipr", "label_wrapped", "label_y",
  "n_case_ppi", "n_control_ppi",
  "pair_key", "partial_protein_seqs",
  "pf_chr", "pf_end", "pf_instance_id", "pf_start",
  "protein_seq_case", "protein_seq_control",
  "pvalue", "raw_key",
  "strand_1", "strand_2",
  "sxmax", "sxmin",
  "t_start", "t_stop",
  "text", "tmp", "track", "transcript",
  "transcript_id_case", "transcript_id_control",
  "transcript_seq_case", "transcript_seq_control",
  "uniprotswissprot",
  "x", "xend", "xmax", "xmin",
  "y", "y_bottom", "y_top", "ymax", "ymin"
))
